export const SAVE_INSTANCE = 'SAVE_INSTANCE';
export const UPDATE_INSTANCE = 'UPDATE_INSTANCE';
export const REMOVE_INSTANCE = 'REMOVE_INSTANCE';
export const SAVE_ATTRIBUTES = 'SAVE_ATTRIBUTES';
export const SAVE_REVIEWS = 'SAVE_REVIEWS';
